### ISSUE TITLE
Unable to Locate

### ISSUE THREAD

**Issue by kmand** [costales/clipboard-to-file#10]
After

sudo add-apt-repository ppa:costales/clipboard-to-file
sudo apt-get update
sudo apt-get install clipboard-to-file

I get

E: Unable to locate package clipboard-to-file

I'm on Ubuntu 23.04, probably the reason. Any workaround. I also cloned with git, but not clear how to install.

**Comment by costales** [comment]
Hi, sorry, but I didn't find a way to manage the clipboard in GTK4, then it
is not available for higher versions
Best regards
