### ISSUE TITLE
Installed on nautilus - menu not showing up

### ISSUE THREAD

**Issue by healgodschildren** [costales/clipboard-to-file#11]
-------[ SKIP THIS TEXT WALL ]-----------------------------------------------------------------------
     I use paste-as-file on my far more productive Windows machine but I'm really trying to get more productive on Linux because I won't use anything past Windows 7. At some point I'll need a new machine that won't support Windows 7, the last truly good operating system. Paste-as-file is insanely useful and I was so pleased to find that there is a similar utility here. May I suggest a rename of the utility to "ClipToFile Coastal"? It pays homage to the developer but is easier for people to remember how to spell. I will send money for this useful utility if it were to work even mostly reliably compared to its Windows counterpart. 

-------[ BEGIN ISSUE DESCRIPTION ]----------------------------------------------------------------
I am not getting any context menu to paste into a new file. I added the repository and installed the program by following your instructions. I see "Clipboard to File" in the right-click context menu but clicking on it does nothing. If there is supposed to be a submenu, then it is not showing up and there is no arrow indicating the existence of a submenu.

Please advise:

Justin Coy
healgodschildren.substack.com
twitter.com/healgodskids

System:
  Kernel: 6.5.0-35-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.6.8 tk: GTK 3.24.33
    wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: MOTILE product: M142 v: Standard serial: <superuser required>
  Mobo: MOTILE model: PF4PU1F v: Standard serial: <superuser required> UEFI: American Megatrends
    v: N.1.03 date: 08/26/2019
Battery:
  ID-1: BAT0 charge: 28.5 Wh (100.0%) condition: 28.5/46.7 Wh (61.0%) volts: 12.8 min: 11.4
    model: standard serial: <filter> status: Full
CPU:
  Info: quad core model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx bits: 64 type: MT MCP
    arch: Zen/Zen+ note: check rev: 1 cache: L1: 384 KiB L2: 2 MiB L3: 4 MiB
  Speed (MHz): avg: 3059 high: 3694 min/max: 1400/2100 boost: enabled cores: 1: 3693 2: 3694
    3: 2954 4: 2954 5: 2462 6: 2462 7: 3303 8: 2955 bogomips: 33537
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    vendor: Tongfang Hongkong driver: amdgpu v: kernel pcie: speed: 8 GT/s lanes: 16 ports:
    active: eDP-1 empty: HDMI-A-1 bus-ID: 03:00.0 chip-ID: 1002:15d8
  Device-2: Chicony HD Webcam type: USB driver: uvcvideo bus-ID: 3-1:2 chip-ID: 04f2:b68b
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: eDP res: 1920x1080 dpi: 158 diag: 354mm (13.9")
  OpenGL: renderer: AMD Radeon Vega 8 Graphics (raven LLVM 15.0.7 DRM 3.54 6.5.0-35-generic)
    v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2 direct render: Yes
Audio:
  Device-1: AMD Raven/Raven2/Fenghuang HDMI/DP Audio vendor: Tongfang Hongkong
    driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s lanes: 16 bus-ID: 03:00.1 chip-ID: 1002:15de
  Device-2: AMD Family 17h HD Audio vendor: Tongfang Hongkong driver: snd_hda_intel v: kernel
    pcie: speed: 8 GT/s lanes: 16 bus-ID: 03:00.6 chip-ID: 1022:15e3
  Sound Server-1: ALSA v: k6.5.0-35-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Tongfang Hongkong
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: f000 bus-ID: 01:00.0
    chip-ID: 10ec:8168
  IF: enp1s0 state: down mac: <filter>
  Device-2: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 bus-ID: 02:00.0 chip-ID: 8086:24fb
  IF: wlp2s0 state: up mac: <filter>
  IF-ID-1: lxcbr0 state: down mac: <filter>
Bluetooth:
  Device-1: Intel Wireless-AC 3168 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 3-2.4:6
    chip-ID: 8087:0aa7
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 2.1 lmp-v: 4.2
    sub-v: 1100
Drives:
  Local Storage: total: 238.47 GiB used: 201.66 GiB (84.6%)
  ID-1: /dev/sda vendor: BIWIN model: SSD size: 238.47 GiB speed: 6.0 Gb/s serial: <filter>
Partition:
  ID-1: / size: 233.18 GiB used: 201.65 GiB (86.5%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 511 MiB used: 9.5 MiB (1.9%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 498 MiB (24.3%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: 75.0 C mobo: N/A gpu: amdgpu temp: 80.0 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: 2700 apt: 2677 flatpak: 23
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/costales-clipboard-to-file-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/costales-clipboard-to-file-jammy.gpg] https: //ppa.launchpadcontent.net/costales/clipboard-to-file/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/google-earth-pro.list
    1: deb [arch=amd64] http: //dl.google.com/linux/earth/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //mirror.team-cymru.com/mint-packages vera main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/teamviewer.list
    1: deb [signed-by=/usr/share/keyrings/teamviewer-keyring.gpg] https: //linux.teamviewer.com/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/waydroid.list
    1: deb [signed-by=/usr/share/keyrings/waydroid.gpg] https: //repo.waydro.id/ jammy main
Info:
  Processes: 321 Uptime: 52m Memory: 5.71 GiB used: 4.31 GiB (75.6%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 5.6.8 inxi: 3.3.13

**Comment by healgodschildren** [comment]
lily@lilitop:~$ sudo su
[sudo] password for lily:       
root@lilitop:/home/lily# apt-get install clipboard-to-file
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
clipboard-to-file is already the newest version (0.0.9).
The following packages were automatically installed and are no longer required:
  libwpe-1.0-1 libwpebackend-fdo-1.0-1 linux-headers-5.15.0-101
  linux-headers-5.15.0-101-generic linux-headers-5.15.0-107
  linux-headers-5.15.0-107-generic linux-image-5.15.0-101-generic
  linux-image-5.15.0-107-generic linux-modules-5.15.0-101-generic
  linux-modules-5.15.0-107-generic linux-modules-extra-5.15.0-101-generic
  linux-modules-extra-5.15.0-107-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
root@lilitop:/home/lily#

**Comment by costales** [comment]
Hi! Thank you for your feedback!
Currently I was not able to do it work in newer Ubuntu releases, then, probably this project will die with the last release 22.04. Best regards!
