### ISSUE TITLE
Clipboard-To-File for Nemo not working

### ISSUE THREAD

**Issue by healgodschildren** [costales/clipboard-to-file#12]
I have installed this useful application but it doesn't seem to work.

I am running Linux Mint 21.1 Cinnamon
I have Nemo 5.6.4

When I right click and select the context menu option "Clipboard-To-File", nothing happens. Is there anything you can do to help?

**Comment by costales** [comment]
Hi,
I think 21.1 should be updated to 21.3 (?).
Just tested and the app is working for me with LM 21.1 & Nemo 6.0.2.
Best regards.
