### ISSUE TITLE
AUR package ?

### ISSUE THREAD

**Issue by Krafting** [costales/clipboard-to-file#4]
Hello there!

I found out about your small extension and I'd love to use it! 

Do you plan to add it to the AUR (and also Fedora CORP ?) at some point so user on arch (or Fedora) could have a easier time downloading it ? :)

Thanks!

**Comment by costales** [comment]
Hi @Krafting !

Thanks for your feedback! I don't use them and I don't know how to package into AUR. If someone could do it, would be great :)

If you want to use in a non Debian base OS, it should be easy:

- Download the [.deb from here](https://launchpad.net/~costales/+archive/ubuntu/clipboard-to-file/+packages) for your file browser (Nautilus, Nemo, Caja):

![image](https://user-images.githubusercontent.com/5886786/197598766-f389e695-49eb-4a2d-bc74-15d8aa3421ed.png)

- Open with File Roller.
- Open `data.tar.zst` file.
- Open `.`
- Copy that `usr` directory into your `/usr`.
- Restart your file browser, for example `nautilus -q`
- It should works.

You should have the languages and the extension (not in GTK4 / Nautilus 43). Could you confirm me please?

A hug.

**Comment by Krafting** [comment]
Your solution works, indeed! Well, I'll use it that way for now until someone make a aur package!

I also contributed French translation on launchpad, if you want to take a look!
