### ISSUE TITLE
Append to file

### ISSUE THREAD

**Issue by gnarlin** [costales/clipboard-to-file#7]
Thanks for this project. I hope one day that this feature becomes default in Gnome (though I won't hold my breath for the Gnome devs to do that).
Since this enables me to dump text to file from the clipboard, could you please also add the ability to append from clipboard to a textfile?
For example: I have a textfile with jokes I find online and every time I find a new one to copy I have to open the text file and paste at the bottom. If I could just right click the file and click something like "Append clipboard to file" that would be fantastic and save me time.

**Comment by costales** [comment]
Hi @gnarlin 
This is an awesome and useful idea! Implemented now! You have it in version 0.0.9.
Please, test it and confirm me if it working :)

```
sudo apt update
sudo apt install clipboard-to-file -y
nautilus -q
```

Thank you so much!

**Comment by gnarlin** [comment]
Tested. It worked :D

**Comment by costales** [comment]
Thank you for the confirmation. Enjoy it! |o/
